version: 1.0
provider:
  name: openfaas
functions:
  addproduct:
    lang: node14
    handler: ./products/addProduct
    image: ${OPENFAAS_PREFIX}/addproduct:latest
    secrets:
      - mysql-connection
      - mongo-connection
  getproducts:
    lang: node14
    handler: ./products/getProducts
    image: ${OPENFAAS_PREFIX}/getproducts:latest
    secrets:
      - mysql-connection
      - mongo-connection
